spring.application.name=sfaneapi
spring.datasource.url=jdbc:postgresql://ep-mute-fire-a1a43b4o-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zt3yHFCP9uXQ

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# JWT configuration
app.jwt.secret=ChangeThisJWTSecretToAStrongRandomString
# 1 hour in milliseconds
app.jwt.expirationMs=3600000

# Optionally configure a default admin password (only for dev)
app.admin.defaultUsername=admin
# change this immediately in production!
app.admin.defaultPassword=admin123

# Refresh token config (ms)
# 7 days
app.jwt.refreshExpirationMs=604800000

